### PR TITLE
Added Russian language

### PR DESCRIPTION
**Pull request by nm17**

### CODE REVIEW

**Review by Astrono2 — CHANGES_REQUESTED** [review]
Pull request #20, which is to be merged soon, requires localization files to now begin with `LANGUAGE_NAME <name>` in the first line, where the language's name is written in that same language. It hasn't been added to the documentation yet.

**Comment by mbrlabs** [comment]
@nm17 thanks for the translation! I just merged @Astrono2's PR, so you would need to add `LANGUAGE_NAME` to this PR now. See also the updated [localization guide](https://github.com/mbrlabs/Lorien/blob/main/docs/i18n.md )

**Comment by nm17** [comment]
@mbrlabs @Astrono2 check it out now

**Comment by mbrlabs** [comment]
Thanks!

**Pull request merged**
