### PR TITLE
Reset tool state on tool change

### LINKED ISSUE #153: Segmentation fault when switching modes mid-stroke
**Lorien version:**
0.5.0

**OS/device including version:**
Fedora 35

**Issue description:**
Drawing on my tablet (using OpenTabletDriver), and it crashed. 

**Steps to reproduce:**
1. Be using tablet with OpenTabletDriver
2. Press eraser hotkey mid-pen-stroke
3. Release pen
4. Re-touch pen to tablet, and SIGSEGV occurs

https://user-images.githubusercontent.com/69441971/173972831-3d5941f9-2a77-490c-a230-ecc0dccb0b2f.mp4

### PR DESCRIPTION
**Pull request by hansemro**
Resolves #153

### CODE REVIEW

**Comment by hansemro** [comment]
TODO: Selection rectangle does not get cleared after changing tool.

**Comment by hansemro** [comment]
Cleaned up fix by having tools implement their own state reset function if it involves clearing additional objects.

**Review by mbrlabs — APPROVED** [review]
Looks and works good! Let me know when this is ready to merge

**Comment by mbrlabs** [comment]
Thanks!

**Pull request merged**
