### PR TITLE
Added a circle tool

### PR DESCRIPTION
**Pull request by lparth**
Added prototype circle tool that works for my immediate needs.
Probably the world's most inefficient circle plot. :) Needs
more Godot knowledge than someone like me who has been hacking
with it for less than a day.

### CODE REVIEW

**Comment by lparth** [comment]
Thank you for developing such a great tool. I needed it for some presentation but I badly needed a circle tool since my drawing skills are such that the curves don't even meet :). So I hacked up something by looking at your RectangleTool patch. I had zero Godot knowledge before started with this patch and the patch definitely needs some love from someone who knows this ecosystem well. So I'll leave the PR at your disposal.

**Comment by mbrlabs** [comment]
Sweet, thanks a lot! :) I'm gonna have a look as soon as possible.

**Comment by mbrlabs** [comment]
I'm closing this in favor of https://github.com/mbrlabs/Lorien/pull/120 which performs a bit better and can also draw ellipses. 
But thank you very much for your contribution nonetheless! ;)

**Comment by lparth** [comment]
Thank you

**Pull request closed without merging**
